"""Primary class for converting sorting data."""
import redis
import numpy as np
from pynwb import NWBFile
from typing import Union, Optional, List, Tuple, Sequence, Literal

from neuroconv.utils import DeepDict
from neuroconv.datainterfaces.ecephys.basesortingextractorinterface import BaseSortingExtractorInterface

from stavisky_lab_to_nwb.redis_interfaces.redissortingextractor import RedisStreamSortingExtractor, redis_add_sorting


class RedisSortingInterface(BaseSortingExtractorInterface):
    """Sorting interface for Stavisky Redis conversion"""
    
    ExtractorModuleName = "stavisky_lab_to_nwb.redis_interfaces.redissortinginterface"
    ExtractorName = "RedisStreamSortingExtractor"
    
    def __init__(
        self,
        port: int,
        host: str,
        stream_name: str,
        data_key: Union[bytes, str],
        unit_count: int,
        dtype: Union[str, type, np.dtype],
        unit_ids: Optional[Sequence] = None,
        frames_per_entry: int = 1,
        timestamps: Optional[np.ndarray] = None,
        start_time: Optional[float] = None,
        sampling_frequency: Optional[float] = None,
        timestamp_source: Union[bytes, Literal["redis"]] = "redis",
        timestamp_kwargs: dict = {},
        unit_dim: int = 0,
        verbose: bool = True,
    ):
        super().__init__(
            verbose=verbose,
            port=port,
            host=host,
            stream_name=stream_name,
            data_key=data_key,
            unit_count=unit_count,
            dtype=dtype,
            unit_ids=unit_ids,
            frames_per_entry=frames_per_entry,
            start_time=start_time,
            sampling_frequency=sampling_frequency,
            timestamp_source=timestamp_source,
            timestamp_kwargs=timestamp_kwargs,
            unit_dim=unit_dim,
        )

    def get_metadata(self):
        # Automatically retrieve as much metadata as possible
        metadata = super().get_metadata()
        
        return metadata

    def add_to_nwbfile(
        self,
        nwbfile: NWBFile,
        metadata: Optional[DeepDict] = None,
        stub_test: bool = False,
        write_ecephys_metadata: bool = False,
        write_as: Literal["units", "processing"] = "units",
        units_name: str = "units",
        units_description: str = "Autogenerated by neuroconv.",
    ):
        """
        Slightly modified version of add_to_nwbfile that uses a custom redis_add_sorting function
        instead of the in-built add_sorting. See source file for details.
        """
        from spikeinterface import NumpyRecording

        from ...tools.spikeinterface import (
            add_devices,
            add_electrode_groups,
            add_electrodes,
            add_sorting,
        )

        if write_ecephys_metadata and "Ecephys" in metadata:
            n_channels = max([len(x["data"]) for x in metadata["Ecephys"]["Electrodes"]])
            recording = NumpyRecording(
                traces_list=[np.empty(shape=n_channels)],
                sampling_frequency=self.sorting_extractor.get_sampling_frequency(),
            )
            add_devices(nwbfile=nwbfile, metadata=metadata)
            add_electrode_groups(recording=recording, nwbfile=nwbfile, metadata=metadata)
            add_electrodes(recording=recording, nwbfile=nwbfile, metadata=metadata)
        if stub_test:
            sorting_extractor = self.subset_sorting()
        else:
            sorting_extractor = self.sorting_extractor
        property_descriptions = dict()
        for metadata_column in metadata["Ecephys"].get("UnitProperties", []):
            property_descriptions.update({metadata_column["name"]: metadata_column["description"]})
            for unit_id in sorting_extractor.get_unit_ids():
                # Special condition for wrapping electrode group pointers to actual object ids rather than string names
                if metadata_column["name"] == "electrode_group":
                    if nwbfile.electrode_groups:
                        sorting_extractor.set_unit_property(
                            unit_id=unit_id,
                            property_name=metadata_column["name"],
                            value=nwbfile.electrode_groups[
                                self.sorting_extractor.get_unit_property(
                                    unit_id=unit_id, property_name="electrode_group"
                                )
                            ],
                        )
        redis_add_sorting(
            sorting_extractor,
            nwbfile=nwbfile,
            property_descriptions=property_descriptions,
            write_as=write_as,
            units_name=units_name,
            units_description=units_description,
        )

        
if __name__ == "__main__":
    extractor = RedisStreamSortingExtractor(
        port=6379,
        host="localhost",
        stream_name="neuralFeatures_1ms",
        data_key=b'threshold_crossings',
        unit_count=256,
        dtype=np.int16,
        unit_ids=None,
        frames_per_entry=1,
        start_time=None,
        sampling_frequency=None,
        timestamps=None,
        timestamp_source="redis",
        timestamp_kwargs={
            "chunk_size": 10000,
            "timestamp_unit": "ms",
            "smoothing_window": 1,
            "smoothing_stride": 1,
        },
    )
    out = extractor.get_all_spike_trains(
        outputs="unit_index",
    )
    times, labels = out[0]
    import pdb; pdb.set_trace()